#!/bin/bash

docker rm ifhany_db; docker compose -f docker-compose.yml -f config/docker-compose_dev.yml up -d

echo "Starting dev mode";

STARTED=false
TRIES=1
while [ $STARTED = false ]; do
    sleep 1;

    echo "Waiting for dev mode to start... ($TRIES)";

    if docker ps | grep -q ifhany_app; then
        STARTED=true;
    fi

    TRIES=$((TRIES + 1))
done

dockersh ifhany_app